policy:
  approval:
  - or:
    - deploy updates
    - submodule updates
    - anointed maintainers say yes

approval_rules:
- name: anointed maintainers say yes
  options:
    allow_contributor: true
    invalidate_on_push: true
  requires:
    count: 1
    teams:
      - "pewresearch/pewanalytics-maintainers"
    write_collaborators: true

- name: deploy updates
  options:
    invalidate_on_push: true
  if:
    only_changed_files:
      paths:
      - '^deploy/.*'

- name: submodule updates
  options:
    invalidate_on_push: true
  if:
    only_changed_files:
      paths:
      - '^src/.*'
