name: unit-tests

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/unit-tests.yaml
      - Makefile
      - pewanalytics/**
      - requirements.txt
      - setup.py
      - tests/**

jobs:
  unit-tests:
    name: unit-tests
    runs-on: labs-runner
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Install python dependencies
        run: |
          while read requirement; do conda install --yes $requirement; done < requirements.txt
          python setup.py install --user

      - name: Lint with flake8
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make python_lint_errors
          make github_lint_flake8

      - name: Run unit tests
        run: |
          make python_test
